### ISSUE TITLE
Missing dependency “sphinx_toolbox”

### ISSUE THREAD

**Issue by flying-sheep** [domdfcoding/enum_tools#38]
## Description
Your package metadata doesn’t say that `sphinx_toolbox` is a dependency.

## Steps to Reproduce
Install package and add the autoenum extensison

```
extensions = [
    ...
    'enum_tools.autoenum',
    ...
]
```

## Actual result:
```console
Extension error:
  Could not import extension enum_tools.autoenum (exception: No module named 'sphinx_toolbox')
```

## Expected result:
Works

## Reproduces how often:
Easily reproduced

## Version

  * Operating System: Arch Linux
  * Python: 3.9
  * enum_tools: 0.6.4

## Installation source
PyPI/pip

**Comment by domdfcoding** [comment]
Sorry about this. I've added a notice to the `autoenum` module documentation that it requires the `sphinx` extra (which is sphinx and sphinx-toolbox). You can specify that the extra should be installed with ``enum_tools[sphinx]`` in your `requirements.txt` etc.

**Comment by flying-sheep** [comment]
Great, thanks! Btw: `requirements.txt` isn’t for abstract dependencies like this. I recommend [putting your dependency specification into `pyproject.toml`](https://www.python.org/dev/peps/pep-0621/) (or for legacy setuptools projects, into `setup.cfg`)
