### ISSUE TITLE
Create multi-line enum member documentation

### ISSUE THREAD

**Issue by 1kastner** [domdfcoding/enum_tools#40]
## Description
 
I would like to do something like this:

```python
@enum_tools.documentation.document_enum
class Test(enum.Enum):
    """
    xxx
    """

    a= 20  # doc: some text
    b= 40  # doc: some more text....
               # doc: and an additional line still referring to b
```

The naive version did not work for me but is there a way to do it?

**Comment by 1kastner** [comment]
@domdfcoding how do you solve doc strings that are longer than the default line length set by pylint (e.g., 80 or 120 characters)? Do you just try to keep the lines short? Is there a trick that I missed which allows me to have a second line?

**Comment by 1kastner** [comment]
Would you accept a corresponding pull request?

**Comment by domdfcoding** [comment]
Sorry for the wait.

#49 should solve this. It will allow you to use the following syntax:

```python3
@enum_tools.documentation.document_enum
class Test(enum.Enum):
    """
    xxx
    """

    a= 20  # doc: some text
    
    """
    some more text....
    and an additional line still referring to b
    """
    b= 40
```

or, for long comments that are only a single line:

```python3
@enum_tools.documentation.document_enum
class Test(enum.Enum):
    """
    xxx
    """

    a= 20  # doc: some text
    
    #: some more text
    b= 40
```

This is the same syntax Sphinx autodoc uses for attribute docstrings, if you are familiar with it.

For the `"""` version blank lines should be preserved. You can see this in the `People` example in the docs (https://enum-tools--49.org.readthedocs.build/en/49/api/autoenum.html#demo)

**Comment by 1kastner** [comment]
Thank you very much! At https://enum-tools--49.org.readthedocs.build/en/49/_modules/enum_tools/demo.html#People, the doc string follows the attribute (see Carol), in the given example ot precedes it. When do we use which approach?

**Comment by 1kastner** [comment]
From https://www.sphinx-doc.org/en/1.5.2/ext/example_google.html I deduced that the docstring should follow the attribute, not preceded it (unlike `#:`).

**Comment by 1kastner** [comment]
On a new branch, I included `enum_tools @ git+https://github.com/domdfcoding/enum_tools@parser-rewrite` in my setup.py. First, I encountered issues in https://github.com/domdfcoding/enum_tools/blob/master/enum_tools/documentation.py#L125 because two additional attributes were requested that did not exist, namely `health` and `environment`. Obviously that is a file from the wrong branch. When realizing this, I recreated the virtual environment I was operating in. Now the documentation is building again.

Now, the following works exactly as expected, thanks a lot for that!
```
@enum_tools.documentation.document_enum
class ModeOfTransport(enum.Enum):

    feeder = "feeder"  # doc: A feeder vessel is a rather small vessel sent by a ship operator and moves in the region

    deep_sea_vessel = "deep_sea_vessel"
    """A deep sea vessel is a rather large vessel sent by a ship operator and moves between distant regions, e.g.
    continents."""

```


Here, I tried to make the docstring preced the attribute like you showed previously:
```
@enum_tools.documentation.document_enum
class ModeOfTransport(enum.Enum):

    feeder = "feeder"  # doc: A feeder vessel is a rather small vessel sent by a ship operator and moves in the region

    """A deep sea vessel is a rather large vessel sent by a ship operator and moves between distant regions, e.g.
    continents."""
    deep_sea_vessel = "deep_sea_vessel"
```
In this case, the feeder (instead of the deep_sea_vessel) gets the long documentation text and no warning is emitted that two different documentation strings are provided (and one overwrites the other). That is obviously not mandatory but it might be extremly helpful (a feature request with low importance I guess).

So thank you very much and I am looking forward for the new version once #49 is merged!

**Comment by domdfcoding** [comment]
> From https://www.sphinx-doc.org/en/1.5.2/ext/example_google.html I deduced that the docstring should follow the attribute, not preceded it (unlike #:).

Sorry about the confusion, that was a typo on my part, You are right that the docstring should go after the attribute, but `#:` goes before the attribute.

> In this case, the feeder (instead of the deep_sea_vessel) gets the long documentation text and no warning is emitted that two different documentation strings are provided (and one overwrites the other). That is obviously not mandatory but it might be extremly helpful (a feature request with low importance I guess).

I hadn't considered that. I have added a warning in 4c26437.

Thanks for your feedback.

**Comment by 1kastner** [comment]
Thank you very much for your implementation!

**Comment by 1kastner** [comment]
Thank you for this additional feature in v0.8!
