### ISSUE TITLE
Make documented enum maintain its type hints?

### ISSUE THREAD

**Issue by 1kastner** [domdfcoding/enum_tools#41]
## Description
After I have added the decorators, my enums do not offer auto completion in PyCharm anymore.

## Version

  * Python: 3.8
  * enum_tools: 0.6.4

## Other Additional Information:
At https://stackoverflow.com/questions/47060133/python-3-type-hinting-for-decorator there is an interesting discussion on how to retain some information after having decorated something.

**Comment by nsofanat1k** [comment]
Hi! This [PR](https://github.com/domdfcoding/enum_tools/pull/42) might solve this problem.

**Comment by 1kastner** [comment]
That sounds fantastic!

**Comment by domdfcoding** [comment]
@1kastner #42 should have solved. I've released [version 0.6.5](https://pypi.org/project/enum-tools/0.6.5/) which includes the fix.

Can you try that version, and if it works for you I'll close this issue.

Sorry for any inconvenience.

**Comment by 1kastner** [comment]
I tried it out and it worked like a charm!

**Comment by 1kastner** [comment]
Thank you very much @domdfcoding for this nice project and effort! There was no inconvenience, just a chance for me to learn a bit more about Python and typehints.
