### ISSUE TITLE
Publish enum_tools at conda-forge?

### ISSUE THREAD

**Issue by 1kastner** [domdfcoding/enum_tools#59]
I would like to use enum_tools for a conda package which I plan to publish at conda-forge. One of my dependencies is your module. As you already made enum_tools available at your own conda channel, would you mind adding conda-forge as an additional channel?

The general issue is that with our own personal channels, we will end up with a long chain of additional channels. Now it is `conda-build -c conda-forge -c domdfcoding my-recipe` for me when building my package on my own channel. But the next person who depends on my work would need to add my personal channel as well, making this chain longer and longer. This is not good practice. Some interesting background knowledge is available at https://github.com/conda-forge/staged-recipes#6-do-all-of-my-packages-dependencies-have-to-be-in-conda-forge-already.

**Quick side note:** This is only necessary because I need enum_tools for the user installation (otherwise the decorators would not be defined). If it was only a dependency for the development installation (as layed out in https://github.com/domdfcoding/enum_tools/issues/50), this step could be skipped.

**Alternative:** A possible workaround would be to define my own wrapper for your library, checking whether it is installed and if it is not available, just make the decorators a no-op. This is by far not my favorite solution.

**Comment by domdfcoding** [comment]
Hi @1kastner, sorry for the wait.

I can absolutely do that. Does your package make use of the Sphinx integration (`enum_tools.autoenum`) or just the other parts (`documentation` and `custom_enums`)? `autoenum` depends on sphinx-toolbox, so I'd have to add sphinx-toolbox and its dependencies to conda-forge too (that's not a problem, it'll just take time).

**Comment by 1kastner** [comment]
Hi @domdfcoding, could you shorty comment on how the process of moving the dependencies of `enum_tools` to conda-forge is going? And, do you think it is reasonable to have two different packages there, one with and one without sphinx-tools? That could result in a similar setup like `matplotlib` and `matplotlib-base`. Then, maybe I could already start to use the decorator `enum_tools.documentation.document_enum`. Thank you very much for your effort!

**Comment by 1kastner** [comment]
By the way, a proposed recipe for `enum_tools` without the optional dependencies can be found at https://github.com/conda-forge/staged-recipes/pull/18124#issuecomment-1086928696

**Comment by 1kastner** [comment]
Thank you very much for your effort and patience! It is great to see the package online [on conda-forge](https://anaconda.org/conda-forge/enum_tools)!
